title: "Mayur Jadhav"
logo: "/src/images/profile/ppf.png"
description: >-
  Data Analyst with 5+ years of experience in data analytics,
  automation, and financial management.<br>
  I love SQL and finding patterns in data and solving hard problems.
# baseurl: "" # Leave this blank for username.github.io
# url: "https://mayurgj.github.io" # Your GitHub Pages URL

# Theme settings
theme: jekyll-theme-minimal

# Author info
author:
  name: "Mayur Jadhav"
  email: "mayurgj1978@gmail.com"

# Social links
github_username: mayurgj
linkedin_username: mayurjadhav

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
